# Generated by Django 5.0 on 2023-12-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('T-SHIRT', 'T-SHIRT'), ('BLAZERS', 'BLAZERS'), ('SUNGLASS', 'SUNGLASS'), ('KIDS', 'KIDS'), ('POLO SHIRT', 'POLO SHIRT')], default=1, max_length=30, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
